### ISSUE TITLE
Git Automator can be used to use "Conventional Commits"?

### ISSUE THREAD

**Issue by gabrielizalo** [ivangabriele/vscode-git-automator#111]
Git Automator can be used to use "[Conventional Commits](https://www.conventionalcommits.org/en/)"?

**Comment by ivangabriele** [comment]
Hi @gabrielizalo,

Sorry for the late answer! As a matter of fact I just started working on the [v3](https://github.com/ivangabriele/vscode-git-automator) which will be way "smarter' and will use Conventional Commits by default. It will developed on a separate repository and extension since it may take some time to make it fully stable.
